### muestra todos los productos
GET http://localhost:8080/products


### need token -> el token se muestra cuando te logueas
GET http://localhost:8080/users
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM


### muestra los carritos de compra
GET http://localhost:8080/cart
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM


###logueo
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "name": "liverlin",
    "password": "bebeloper123"
}

### crear cuenta
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "name": "Elon Mosk",
    "email": "x@twiter.com",
    "password": "password"
}

### crear usuario -> lo mismo xd
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "name": "dfsbdf dfvsfd",
    "email": "fdsgdfsg@gmail.com",
    "password": "password",
    "role":"1"
}


### add product
POST http://localhost:8080/products
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM

{
    "name": "lenovo-gbdfg",
    "description": "pal mainchah",
    "img": "legion",
    "price": 7,
    "qty": 50
}


### add other product :v -> think pad
POST http://localhost:8080/products
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM

{
    "name": "lenovo-thinkpad",
    "description": "pa la mina :v",
    "img": "thinkpad",
    "price": 7,
    "qty": 15
}

### elimina producto
DELETE http://localhost:8080/products/6585385ceeab98258e0d0767
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM


### elimnia carrito
DELETE http://localhost:8080/cart
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM


### edita producto -> ideapad
PATCH  http://localhost:8080/products/658537e8eeab98258e0d0758
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM

{
    "qty": 200
}


###
POST http://localhost:8080/cart/6229d82eeda4cf8db56f1392
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM

{
    "qty": 20
}


###
PUT http://localhost:8080/cart/6229d82eeda4cf8db56f1392
Content-Type: application/json
x-access-token: fdkjgbdfs.eyJpZzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM

{
    "qty": 5
}


### update carrito
PATCH http://localhost:8080/cart/6229d82eeda4cf8db56f1392
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM


### 
DELETE http://localhost:8080/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM


### update name of user
PATCH http://localhost:8080/user
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODUyNzgzZDVmNDU2NjlmNjdkZGRkYSIsImlhdCI6MTcwMzIyOTI0OCwiZXhwIjoxNzAzMzE1NjQ4fQ.X9sXuwhBsz2mD_nE0ywZtdgGmWdboBGSfi-aFQh9_LM

{
    "name": "Pocoyo 1234"
}